apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: traefik
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: traefik
spec:
  destination:
    name: ui
  sources:
    - name: traefik
      permissions:
        - action: allow
          http:
            pathExact: /
            methods: ['GET']
        - action: allow
          http:
            pathPrefix: /ui
            methods: ['GET']