apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: example-kong-proxy
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: kong
spec:
  destination:
    name: ui
  sources:
    - name: example-kong-proxy
      permissions:
        - action: allow
          http:
            pathExact: /
            methods: ['GET']
        - action: allow
          http:
            pathPrefix: /ui
            methods: ['GET']